### ISSUE TITLE
Implement Landing, Signup, and Login Pages

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#1]
Implement Landing, Signup, and Login Pages according to the UI design provided in the linked Figma file. Image used in the webpage is provided in **"image"** folder.

**Step to follow:**

1. Fork this repository and clone it into your local system
2. Go to client > component > Landing , Sign up, Login page folder.
3. Then add your code in that folder

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by TheDivineAurora** [comment]
claim

**Comment by ghost** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned @nitusherawat

**Comment by Nitu-Sherawat** [comment]
claim

**Comment by Tiyasa9** [comment]
Assigned to @Nitu-Sherawat

**Comment by Aryan4884** [comment]
claim

**Comment by Nandinig24** [comment]
claim

**Comment by Aryan4884** [comment]
claim

**Comment by Sindhu194** [comment]
claim

**Comment by Tulsi5990** [comment]
claim

**Comment by chiragmalik2612** [comment]
claim

**Comment by Nitu-Sherawat** [comment]
I am unable to solve this issue.

**Comment by Hannah2k23** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by shrutikarathi6** [comment]
Claim

**Comment by Tiyasa9** [comment]
Assigned to @Hannah2k23

**Comment by rnavaneeth992** [comment]
Claim

**Comment by kushal7201** [comment]
c

**Comment by Nivedh-Biju** [comment]
claim

**Comment by GovindaRohith** [comment]
Claim

**Comment by AngadManroy** [comment]
Claim

**Comment by Hannah2k23** [comment]
Sorry, I won't be able to solve this issue in time

**Comment by Tiyasa9** [comment]
Hey! @Hannah2k23 
How much time will you require to complete the task?

**Comment by Hannah2k23** [comment]
3 days more as I am yet to develop the skill required to complete this task

**Comment by riri-2k3** [comment]
claim

**Comment by Tiyasa9** [comment]
Hey @Hannah2k23 !!

No worries... You may work on the other issues that are live and many more are yet to come. You may start with Task4 since it is a beginner-friendly issue which would give you a great start. Thank you :)

**Comment by QuantTitan** [comment]
claim

**Comment by Nandinig24** [comment]
claim

**Comment by Tiyasa9** [comment]
Assigned to @Nandinig24

**Comment by Meenakshi233** [comment]
claim
