### ISSUE TITLE
Configure mongodb

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#10]
Configure mongoDB using mongoose and set the connection url as env variable MONGODB_URL in [db.config.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/config/db.config.js)

**Comment by DIWAKARKASHYAP** [comment]
cliaim

**Comment by Oshankiii12** [comment]
This is girls only repo

**Comment by anukraticodes** [comment]
claim

**Comment by Reene-Simon** [comment]
Claim

**Comment by Aswinr24** [comment]
Claim

**Comment by Oshankiii12** [comment]
assigned to @anukraticodes congratulations 🎉

**Comment by DIWAKARKASHYAP** [comment]
> This is girls only repo
where is equality ?

**Comment by Nandinig24** [comment]
Claim

**Comment by Nivedh-Biju** [comment]
claim

**Comment by GovindaRohith** [comment]
Claim

**Comment by riri-2k3** [comment]
claim

**Comment by Oshankiii12** [comment]
updates? @anukraticodes

**Comment by chhaviyadav1293** [comment]
Claim

**Comment by Oshankiii12** [comment]
Assigned to @chhaviyadav1293 !

**Comment by chhaviyadav1293** [comment]
Now I've registered

**Comment by Oshankiii12** [comment]
Assigned to @chhaviyadav1293
