### ISSUE TITLE
Implement Profile page

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#16]
_Hola Contributors!!_

_In this task, you are supposed to **implement the Profile page** of EasyExit website as per the UI Design in the figma link. But this time, you can also **show your creativity**, you may add new features to the page(keeping the basic structure and profile form intact), add new styles etc._

**Step to follow:**

1. Fork this repository and clone it into your local system
2. Go to client > component > Profile page folder.
4. Then add your code in that Profile page folder

For any queries feel free to reach out to us.

**THIS IS A COMPETITIVE ISSUE. NO NEED TO CLAIM. SUBMISSIONS WILL BE ACCEPTED TILL  17 DEC 2023 11:49am.**

**Comment by Nandinig24** [comment]
claim

**Comment by shrutikarathi6** [comment]
Claim
