### ISSUE TITLE
Design a logo for project EasyExit

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#2]
**OPEN TO ALL.
You don't need to claim this issue.**

EasyExit is a project that aims to simplify the process of issuing, approving, and verification of GatePass for college students.
Enter your GitHub account and attach the Figma link in the [design.json](https://github.com/opencodeiiita/EasyExit/blob/main/designs.json) file.

**Comment by Rohit-110** [comment]
@Oshankiii12  Is the task for everyone or girls-only ?

**Comment by Oshankiii12** [comment]
> @Oshankiii12 Is the task for everyone or girls-only ?

No its girls-only
