### ISSUE TITLE
Create user model 

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#22]
Create the user database model in the [models > user.model.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/models/user.model.js) file. The information regarding the same is available in the [README.md](https://github.com/opencodeiiita/EasyExit/blob/main/README.md) file.

**Comment by apricity24** [comment]
Claim

**Comment by Oshankiii12** [comment]
Assigned to @apricity24
