### ISSUE TITLE
Create GatePass Form model 

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#26]
Create the form database model in the [models > form.model.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/models/form.model.js) file. The information regarding the same is available in the [README.md](https://github.com/opencodeiiita/EasyExit/blob/main/README.md) file.

For any doubts or difficulty, you can ping me on Discord, I'll try to help you out as soon as possible.

**All the Best!!**

**Comment by shahswati098** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned to @shahswati098 . You have 48 hours for this task.
Happy Contributing!!

**Comment by shrutikarathi6** [comment]
claim

**Comment by Oshankiii12** [comment]
Updates @shahswati098 ?

**Comment by shahswati098** [comment]
Working on it

**Comment by abhisheksharma010** [comment]
Claim
