### ISSUE TITLE
Create Student GatePass form page

### ISSUE THREAD

**Issue by saiushasree1** [opencodeiiita/EasyExit#28]
Implement Student viewpage consisting of form to apply for new Gatepass according to the UI design provided in the linked Figma file.

Step to follow:

Fork this repository and clone it into your local system
Go to client > component > Student Gate Pass Form.
Then add your code in that folder
For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by shrutikarathi6** [comment]
claim

**Comment by saiushasree1** [comment]
Hello @shrutikarathi6,You have 48hours from now to complete the task
Keep Contributing :) 
All the best!!!

**Comment by Nandinig24** [comment]
Claim

**Comment by abhisheksharma010** [comment]
Claim
