### ISSUE TITLE
Write a function to hash user passwords

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#29]
Write a function in [utils > password.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/password.js) that will convert a password string to a secured hash. You can use SECRET environment variable if required. Return type should be string.

For any doubts or difficulty, you can ping me on Discord, I'll try to help you out as soon as possible.

**All the Best!**

**Comment by abhisheksharma010** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by Shweta-1902** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned to @Nandinig24 
You have 48 hours to complete this task. Happy Contributing!

**Comment by abhisheksharma010** [comment]
Why it's not assigned to me

**Comment by Oshankiii12** [comment]
@abhisheksharma010 This repository is designated exclusively for girls, meaning only female contributors are invited. Regrettably, your participation does not apply to this particular project. However, we warmly welcome your contributions to other repositories.
Thank you and happy contributing!

**Comment by abhisheksharma010** [comment]
Sorry I did not read it

**Comment by Oshankiii12** [comment]
update @Nandinig24 ?

**Comment by Nandinig24** [comment]
Submitted
