### ISSUE TITLE
Create the Login functionality for the project.

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#33]
Like every other application, this also requires login functionality. The basic process of this functionality for a REST API is to first check the user credentials and return an error response if they are wrong. On successful verification of the user's credentials, the server should return a secret (JWT token in this case) to the User. The same secret will same be used in the future to verify which user is raising a request to the server.

## The Task
The Login functionality will be written in a function in the file [controllers > auth.controller.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/controllers/auth.controller.js). The function attributes are the default attributes of a request handling function, i.e., (req, res).

Request Parameters:
```
{
  "email": "test@test.com",
  "password": "mY-pAsSwOrD",
  "role": "Student"
}
```
Response Data:
```
{
  "name": "User Name",
  "email": "test@test.com",
  "role": "Student",
  "secret": "JWT Token"
}
```

For checking the password, you will have to first convert the password into hash, the hash_password function present in the [utils > password.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/password.js) should help in converting password into hash. Now you will have to match this hash to the password stored in the database.

Once the user is successfully verified, you will have to create a User Secret, which is actually a JWT token. For creating this JWT token, you have to use the getJwt function present in the [utils > password.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/password.js)

To make returning a response easier, some pre-defined response functions according to the status code of the response are written in [utils > responseCodes.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/responseCodes.js). It is recommended to use them for returning successful or error response. 

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by Nitu-Sherawat** [comment]
claim

**Comment by priyankasharma2823** [comment]
claim

**Comment by Oshankiii12** [comment]
you need to register before claiming the task.

**Comment by priyankasharma2823** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned to @priyankasharma2823, congratulations!!
You have 48 hours to complete this task.
