### ISSUE TITLE
Implement Status page for Students

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#35]
Hello Contributors!!

_In this task you are supposed to implement the page showing the **Status of filled passes for students**. The status will be shown as **"Pending"** until it get approval from the admin. After approval it will show **"Accepted"**. Kindly follow the UI design provided in the Figma link._It is recommended to keep the UI design intact.

**STEPS TO FOLLOW:**

1. Fork this repository and clone it into your local system.
2. Go to client > component. Then create a new folder named **"Status_students"**
3. Add your code in that folder.

In case of any query feel free to reach out to us.

**DEADLINE: 28th Dec 2023 11:00 am**

Happy Contributing!!

**Comment by abhisheksharma010** [comment]
Claim

**Comment by Nandinig24** [comment]
Claim

**Comment by Tiyasa9** [comment]
Assigned to @Nandinig24

**Comment by Nandinig24** [comment]
please unassign me
