### ISSUE TITLE
Create the signup functionality for the project 

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#37]
The entry point to every application is mostly Signup. The basic process of this functionality for a REST API is to first check the user details if they are valid to create an account or not, if they are, the account is created and the user is logged in.

## The Task
The Signup functionality will be written in a function in the file [controllers > auth.controller.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/controllers/auth.controller.js). The function attributes are the default attributes of a request handling function, i.e., (req, res).

The first task is to verify the details entered by the user, i.e., the name is valid or not, email is valid or not and the password's length is greater than 6 characters or not. If any of the following criteria is not matched an error response should be sent. Also check if a user does not already exist with the same email address.

The password should not be saved directly in the database, instead, it should be converted into hash and the hash should be stored in the database, the hash_password function present in the [utils > password.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/password.js) should help in converting password into hash.

Once the user is successfully created, you will have to create a User Secret, which is actually a JWT token. For creating this JWT token, you have to use the getJwt function present in the  [utils > password.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/password.js) and the structure of payload object for this function is this:

To make returning a response easier, some pre-defined response functions according to the status code of the response are written in [utils > responseCodes.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/utils/responseCodes.js). It is recommended to use them for returning successful or error response. The message passed to this function should be something related to the response, as they are for developer reference, the data passed to this function is the same as present in the Response structure present in this file.

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by chhaviyadav1293** [comment]
Claim

**Comment by Oshankiii12** [comment]
Assigned to @chhaviyadav1293 congratulations 🎊
You have 48 hours to complete this task!
