### ISSUE TITLE
Creating a middleware for checking if user is authenticated as student or not

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#39]
In the [middlewares > student.middleware.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/middlewares/student.middleware.js) create a function with arguments: (req, res, next) and export as default export of the file.
# Working of the function:

Check if there is an Authorization header present in the request. If there is, its format should be ```Bearer <token>```.
Absence of this header means the request is unauthorized.
Extract the token from the Authorization header and verify this token if it is valid and has not expired yet.
If the token is verified and user role is set as ```Student``` set req.isAuthenticated = true otherwise set req.isAuthenticated = false.
The User's details will be available in the payload, you will have to find the user in the database using these details and save it to req.user.

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by priyankasharma2823** [comment]
Claim

**Comment by Oshankiii12** [comment]
Assigned to @priyankasharma2823
