### ISSUE TITLE
Implement the pending passes page for admin

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#40]
Hello Contributors!!

In this task you are supposed to implement the **pending passes page for admin** according to the UI design provided in the Figma link.

**STEPS TO FOLLOW:**

_1. Fork this repository and clone it into your local system.
2. Go to client > component. Then create a new folder named "PendingPasses_Admin"
3. Add your code in that folder._

 In case of any query feel free to reach out to us.

YOU HAVE 48HOURS TO COMPLETE THE TASK.

Screenshot of the page to be implemented has been attached for your reference.
![For Admin(To accept pending passes)](https://github.com/opencodeiiita/EasyExit/assets/123008242/72957440-bfc7-4e08-8a9e-09061d6c231e)
![For Admin(To accept pending passes)-1](https://github.com/opencodeiiita/EasyExit/assets/123008242/adf0c64e-8d53-41b8-9982-f3c04547401e)

**Comment by Parth4git** [comment]
claim

**Comment by AditiGupta976** [comment]
claim
