### ISSUE TITLE
Implement OTP verification page for Guard

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#42]
Hello Contributors!!

In this task you are supposed to implement the **OTP verification page for guard** according to the UI design provided in the Figma link.

**STEPS TO FOLLOW:**

_1. Fork this repository and clone it into your local system.
2. Go to client > component. Then create a new folder named "OTP_Guard"
3. Add your code in that folder._

In case of any query feel free to reach out to us.

YOU HAVE 48HOURS TO COMPLETE THE TASK.

Screenshot of the page to be implemented has been attached for your reference.

![For Guard(OTP verification)](https://github.com/opencodeiiita/EasyExit/assets/123008242/7712d5d2-7f5b-4d69-b7c7-22aa618bcee5)

**Comment by Shabbir-Building** [comment]
Hey Tiyasa,

Hope you are doing well. I have checked what you are looking for. I am interested on assisting you. You can assign this issue to me.

However, I have a question. 
Would there be two tabs or only one table and the other one be placeholder?.

Please let me know.

Best,
Shabbir

**Comment by Tiyasa9** [comment]
Hey @Sabbirfeni ,

Thank you for showing interest but for your kind information this is a girls-only-repository encouraging participation from female contributors.

Thank You :)

**Comment by Shabbir-Building** [comment]
Oh! you did not mention that. However, thank for let me know. Have a good one.

Thanks,
Shabbir

**Comment by Mannxxx** [comment]
Claim
