### ISSUE TITLE
Write the controller function to update user's password

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#46]
Request Structure :
```
{
  "oldPassword": "older One",
  "newPassword": "newer One"
}
```
> ### Note

> * You'll have to check user's old password before setting new one.
> * You'll have to write the function in [controllers > user.controller.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/controllers/user.controller.js).
> * Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by priyankasharma2823** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned to @priyankasharma2823 Congratulations!!
You have 24 hours to complete this task.
