### ISSUE TITLE
Write the function for the user to get their profile.

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#49]
Write the controller for the user to get his profile.

### Request Structure :-
```
{
  "name": "User's name",
  "email": "test@test.com",
  "role": "Student"
}
```

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by chhaviyadav1293** [comment]
claim

**Comment by Oshankiii12** [comment]
Assigned to @chhaviyadav1293
