### ISSUE TITLE
Implement frontend of the verification page for Guard

### ISSUE THREAD

**Issue by Tiyasa9** [opencodeiiita/EasyExit#50]
Hello Contributors!!

In this task you are supposed to implement the frontend of the **verification page for guard** according to the UI design provided in the Figma link.

**STEPS TO FOLLOW:**

_1. Fork this repository and clone it into your local system.
2. Go to client > component. Then create a new folder named "VP_Guard"
3. Add your code in that folder._

In case of any query feel free to reach out to us.

YOU HAVE **48HOURS** TO COMPLETE THE TASK.

Screenshot of the page to be implemented has been attached for your reference.

![For Guard(Outpass verification)](https://github.com/opencodeiiita/EasyExit/assets/123008242/d5bdcf68-7e58-4c57-b937-9e04964c9dc0)

**Comment by Mannxxx** [comment]
Claim

**Comment by Tiyasa9** [comment]
Hey @Mannxxx !!

Thank you for your interest. But for your kind information today by the end of the day you need to submit your PR completing the task to get it merged. I can assign the task if you are willing to complete it by end of the day.

**Comment by Mannxxx** [comment]
@Tiyasa9, Is it fine? I'll make a PR once you approve.

![image](https://github.com/opencodeiiita/EasyExit/assets/107349957/837cd4e9-a448-4039-9f62-30ff0e93961e)

(I didn't know which font and exact colour code was used in that Figma image.)
