### ISSUE TITLE
Write the function for the admin to get all pending passes.

### ISSUE THREAD

**Issue by Oshankiii12** [opencodeiiita/EasyExit#52]
Write the controller for the admin to get all pending outpasses, accepted outpasses and rejected outpasses in [controllers> admin.controller.js](https://github.com/opencodeiiita/EasyExit/blob/main/src/controllers/admin.controller.js).

### Note :
* For Pending outpasses, search for forms with ```isAccepted : null``` in the database and return the result.
* For Accepted outpasses, search for forms with ```isAccepted : true``` in the database and return the result.
* For Rejected outpasses, search for forms with ```isAccepted : false``` in the database and return the result.

Make sure to pull before starting your work.

For any doubts or difficulty, you can ping me on discord, I'll try to help you out as soon as possible.

All the Best!!

**Comment by Mannxxx** [comment]
claim (I'm a girl)

**Comment by Oshankiii12** [comment]
Assigned to @Mannxxx 
You have 24 hours to complete this task!!
